// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKcouKRmj5xo-5FZ3mZHhpwt_4M5rCHgQ',
    appId: '1:333188318051:web:8760ac771f6e5aa71a0956',
    messagingSenderId: '333188318051',
    projectId: 'ju-event-management-planner',
    authDomain: 'ju-event-management-planner.firebaseapp.com',
    storageBucket: 'ju-event-management-planner.appspot.com',
    measurementId: 'G-YSK94HR7N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAMFJ190lUpBvY3od1dA-vPBDbxEWDyBg',
    appId: '1:333188318051:android:74b45b2b073528651a0956',
    messagingSenderId: '333188318051',
    projectId: 'ju-event-management-planner',
    storageBucket: 'ju-event-management-planner.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzM-B6a3Z6Jf0H3cIC41dWG5VMoG_GzIM',
    appId: '1:333188318051:ios:f09a8f8e239467841a0956',
    messagingSenderId: '333188318051',
    projectId: 'ju-event-management-planner',
    storageBucket: 'ju-event-management-planner.appspot.com',
    iosBundleId: 'com.example.juEventManagmentPlanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzM-B6a3Z6Jf0H3cIC41dWG5VMoG_GzIM',
    appId: '1:333188318051:ios:f09a8f8e239467841a0956',
    messagingSenderId: '333188318051',
    projectId: 'ju-event-management-planner',
    storageBucket: 'ju-event-management-planner.appspot.com',
    iosBundleId: 'com.example.juEventManagmentPlanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKcouKRmj5xo-5FZ3mZHhpwt_4M5rCHgQ',
    appId: '1:333188318051:web:ce35887339c99ab41a0956',
    messagingSenderId: '333188318051',
    projectId: 'ju-event-management-planner',
    authDomain: 'ju-event-management-planner.firebaseapp.com',
    storageBucket: 'ju-event-management-planner.appspot.com',
    measurementId: 'G-N4WMKK9779',
  );
}
